============================= test session starts =============================
platform win32 -- Python 3.11.9, pytest-8.3.5, pluggy-1.5.0 -- C:\Users\MonalishaRabha\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe
cachedir: .pytest_cache
metadata: {'Python': '3.11.9', 'Platform': 'Windows-10-10.0.26100-SP0', 'Packages': {'pytest': '8.3.5', 'pluggy': '1.5.0'}, 'Plugins': {'allure-pytest': '2.14.3', 'html': '4.1.1', 'metadata': '3.1.1', 'rerunfailures': '15.1', 'xdist': '3.7.0'}}
rootdir: C:\Users\MonalishaRabha\Desktop\vscode\build-1.2 copy
configfile: pytest.ini
testpaths: tests
plugins: allure-pytest-2.14.3, html-4.1.1, metadata-3.1.1, rerunfailures-15.1, xdist-3.7.0
collecting ... collected 0 items / 1 error

=================================== ERRORS ====================================
______________ ERROR collecting tests/script_recording1_test.py _______________
ImportError while importing test module 'C:\Users\MonalishaRabha\Desktop\vscode\build-1.2 copy\tests\script_recording1_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\importlib\__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests\script_recording1_test.py:5: in <module>
    from Utils.base import BaseTest
Utils\base.py:5: in <module>
    from Utils import login
Utils\login.py:5: in <module>
    from Utils import Interactions
Utils\Interactions.py:11: in <module>
    from openpyxl import Workbook, load_workbook
E   ModuleNotFoundError: No module named 'openpyxl'
- generated xml file: C:\Users\MonalishaRabha\Desktop\vscode\build-1.2 copy\reports\report.xml -
- Generated html report: file:///C:/Users/MonalishaRabha/Desktop/vscode/build-1.2%20copy/reports/report.html -
=========================== short test summary info ===========================
ERROR tests/script_recording1_test.py
!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
============================== 1 error in 0.58s ===============================
